server:
  port: 8080

spring:
  profiles:
    active: test   # test 默认开发,打包发布时修改
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 如果需要认证可配置如下
  # username: nacos
  # password: nacos
  # access-token: your-token
